### ISSUE TITLE
Dependency installation fail

### ISSUE THREAD

**Issue by Jerome1337** [formapro/FpOpenIdBundle#103]
I'm trying to use your bundle by installing it like the doc said but when i'm executing ``` $ composer update ```

This is the output
``` 
Problem 1
- fp/openid-bundle dev-master requires lightopenid/lightopenid * -> no matching package found.
``` 

This is a bundle dependency problem ?
I'm using symfony 2.8

Thanks

**Comment by makasim** [comment]
the doc has to be fixed, lightopenid/lightopenid does not have stable version yet. change it to `dev-master`.

https://packagist.org/packages/lightopenid/lightopenid
