### ISSUE TITLE
The login could not be finsih due to token lost.

### ISSUE THREAD

**Issue by makasim** [formapro/FpOpenIdBundle#54]
The provider (FOSUSerManager for example) cannot refreshUser because it is a serialized proxy class. So when you call getId method it will try to load an entity and faild to do it.

**Comment by me1ifaro** [comment]
@makasim, I have enabled ```fetch="EAGER"``` but still token is lost, could you please give me some points?

**Comment by me1ifaro** [comment]
Or maybe I just using something wrong, I interactively create user and I am getting this exception:
```php
if (false == $token instanceof OpenIdToken) {
            throw new \LogicException('The failure does not contain OpenIdToken, Is the failure come from openid?');
}
```

**Comment by me1ifaro** [comment]
Sorry, this was not the point.
