### ISSUE TITLE
lightopenid dependency: gitorious is shutting down

### ISSUE THREAD

**Issue by dbu** [formapro/FpOpenIdBundle#99]
just a quick note that lightopenid that is hosted on google code and was provided through gitorious is no longer installable because gitorious is shutting down. reported in https://code.google.com/p/lightopenid/issues/detail?id=84&thanks=84&ts=1436191471 but until they sort the problem out, people will need to keep their own clone of the repo...

**Comment by dbu** [comment]
and @Mewp already moved the code to github so people just need to update their composer.lock file

**Comment by makasim** [comment]
Cool
